name: flutter_glados
description: "A simple testing framework that tries to break your properties. With Flutter support."
version: 1.1.9

repository: https://github.com/MarcelGarus/glados

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  analyzer: ^5.2.0
  build: ^2.0.0
  characters: ^1.1.0
  meta: ^1.3.0
  source_gen: ^1.0.0
  test: ^1.24.3
  flutter_test:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
